### PR TITLE
Add handling for private ssh key in Git configuration. #52

### PR DESCRIPTION
**Pull request by SINGS079**

### CODE REVIEW

**Comment by SINGS079** [comment]
I was looking how to add the public key to the bare repo and could not figure out how to do that.
Posted a question in Jgit forum https://www.eclipse.org/forums/index.php/t/1094930/ but that also didn't help.
Can you show some pointers on how to write the test case for this scenario?

**Comment by cescoffier** [comment]
Good question. Did you test it against a private repo? 

Also, did you signed the Eclipse CLA?

**Comment by SINGS079** [comment]
Yes, I tested this against my private repo.

And I haven't signed the Eclipse CLA.

**Comment by SINGS079** [comment]
I just signed the Eclipse CLA.
Thanks.

**Comment by cescoffier** [comment]
Thanks!

**Comment by SINGS079** [comment]
Thanks for accepting the pull request. 
Any help on how can we update the documentation?

**Comment by cescoffier** [comment]
@SINGS079 I realized you did update the asciidoc file. So it's fine.

**Pull request merged**
